version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: development-environment-container
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/app/node-attendance-api

volumes:
  db_volume:
    external: false
