version: "3"

services:
  tests:
    build: .
    container_name: tests-environment-container
    env_file:
      - .env.test

  dev:
    build: .
    container_name: development-environment-container
    restart: unless-stopped
    depends_on:
      - tests
    links: 
      - "tests:tests"
    ports:
      - "${PORT}:3000"
    env_file:
      - .env

