version: "3"

services:
  test:
    build: .
    command: yarn test
    container_name: tests-environment-container
    env_file:
      - .env.test

  dev:
    build: .
    command: yarn dev
    container_name: development-environment-container
    restart: unless-stopped
    depends_on:
      - test
    ports:
      - "${PORT}:3000"
    env_file:
      - .env

